### ISSUE TITLE
e

### ISSUE THREAD

**Issue by iogf** [vporton/algebraic-general-topology#1]

**Comment by vporton** [comment]
@iogf Is spreading in the Internet misinformation about me. He is a madman and a fascist.

The real situation was the following:

He welcomed me to work with him on a software project, I am not knowing that he is a fascist, agreed. After some time he [refused to fix an error in the project](https://portonsoft.wordpress.com/2019/08/14/the-worst-software-startup-ever/) due to his feeling of superiority ("I am a good programmer, I will decide the code.") I had no other choice than to fork the project.

In the meantime @iogf drunked and I was sending him much money for him not to die of hunger and work on our common project. When I was unable to make living of two people on my earnings and my money went out I warned @iogf that we need to launch the project as soon as possible and this is the last chance to fix the error he is refusing to fix (claiming like "I am a superhuman." or like this) and he refused to merge my commit fixing his error, I forked. But his project was unmanageable and I closed the project.

Now he is revenging me for stopping to send him money for nothing.

I am attaching a transcript of our correspondence in WhatsApp.
[Oliveira.docx](https://github.com/vporton/algebraic-general-topology/files/4021721/Oliveira.docx)

Yes, he is a fascist: "I dont do deal with evangelic ppl, russians, jewish, niggers nor gypsies anymore. You and haris were the first and last ones."
